# Generated by Django 5.0.2 on 2024-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
