# Generated by Django 5.0.2 on 2024-02-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
            options={
                'verbose_name': 'CTA1',
            },
        ),
        migrations.CreateModel(
            name='CTA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
            options={
                'verbose_name': 'CTA2',
            },
        ),
        migrations.CreateModel(
            name='CTA3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
            options={
                'verbose_name': 'CTA3',
            },
        ),
        migrations.CreateModel(
            name='CTA4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
            options={
                'verbose_name': 'CTA4',
            },
        ),
        migrations.CreateModel(
            name='FeaturedGamesCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured_games_cta__image')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_image')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deal_pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_deals_set', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_games_deal_1', to='Pages.deal')),
                ('deal_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_games_deal_2', to='Pages.deal')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_genres_genre_1', to='Products.genre')),
                ('genre_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_genres_genre_2', to='Products.genre')),
            ],
        ),
        migrations.CreateModel(
            name='PlaystationDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('deal_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playstation_deal_1', to='Pages.deal')),
                ('deal_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playstation_deal_2', to='Pages.deal')),
            ],
        ),
        migrations.CreateModel(
            name='PreOwnedDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('deal_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_owned_deal_1', to='Pages.deal')),
                ('deal_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_owned_deal_2', to='Pages.deal')),
            ],
        ),
        migrations.CreateModel(
            name='TopAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='top_accessories', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='TopDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('deal_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_deal_1', to='Pages.deal')),
                ('deal_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_deal_2', to='Pages.deal')),
                ('deal_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_deal_3', to='Pages.deal')),
                ('deal_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_deal_4', to='Pages.deal')),
            ],
        ),
        migrations.CreateModel(
            name='TopGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='top_games', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='TopHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='top_hardware', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='XboxDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('deal_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xbox_deal_1', to='Pages.deal')),
                ('deal_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xbox_deal_2', to='Pages.deal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='featuredgames',
            constraint=models.UniqueConstraint(fields=('deal_1', 'deal_2'), name='unique_featured_games_deals'),
        ),
        migrations.AddConstraint(
            model_name='featuredgenres',
            constraint=models.UniqueConstraint(fields=('genre_1', 'genre_2'), name='unique_featured_genres'),
        ),
        migrations.AddConstraint(
            model_name='playstationdeals',
            constraint=models.UniqueConstraint(fields=('deal_1', 'deal_2'), name='unique_playstation_deals'),
        ),
        migrations.AddConstraint(
            model_name='preowneddeals',
            constraint=models.UniqueConstraint(fields=('deal_1', 'deal_2'), name='unique_pre_owned_deals'),
        ),
        migrations.AddConstraint(
            model_name='topdeals',
            constraint=models.UniqueConstraint(fields=('deal_1', 'deal_2', 'deal_3', 'deal_4'), name='unique_top_deals'),
        ),
        migrations.AddConstraint(
            model_name='xboxdeals',
            constraint=models.UniqueConstraint(fields=('deal_1', 'deal_2'), name='unique_xbox_deals'),
        ),
    ]
