# Generated by Django 5.0.2 on 2024-02-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_created_at_order_is_completed_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
