# Generated by Django 5.0.2 on 2024-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='genres_set', to='Products.genre'),
        ),
    ]
