# Generated by Django 5.0.2 on 2024-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='Products.genre'),
        ),
    ]
