# Generated by Django 5.0.2 on 2024-02-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.subcategory'),
        ),
    ]
